<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="stylesheet.css">
	<title>Liste des commandes</title>
</head>
<body>
	<h1>Bons de commandes</h1>
	<a href="product.php">Liste des produits</a>
	<table>
		<caption>Liste des commandes</caption>
		<tr>
			<th>Commande</th>
			<th>Date de la commande</th>
			<th>Date de livraison</th>
			<th>Statut</th>
		</tr>
		<?php foreach ($result as $key => $value) { ?>
		<tr>
			<td><a href="detail.php?id=<?php echo $value[0] ?>"><?php echo $value[0] ?></a></td>
			<td><?php echo $value[1] ?></td>
			<td><?php echo $value[2] ?></td>
			<td><?php echo $value[3] ?></td>
		</tr>
		<?php } ?>
	</table>
</body>
</html>