<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="stylesheet.css">
	<title>Liste des commandes</title>
</head>
<body>
	<h1>Produits</h1>
	<a href="index.php">Retour à l'accueil</a><br>
	<a href="product.php">Retour à la liste des produits</a>
	<h2 class="caption h2"><?php echo $result[0][0]; ?></h2>
	<form name="formbarre" method="POST">
	<input type="search" name="barre" id="barre" placeholder="Recherche..." />
	<button type="submit" name="Search">Rechercher</button>
	</form>
	<main  class="flex">
	<?php foreach ($result as $key => $value) { ?>
	<section>
		<h3><?php echo $value[1] ?></h3>
		<p>Stock: <?php echo $value[2] ?></p>
		<p><?php echo $value[3] ?>$</p>
	</section>
	<?php } ?>
	</main>
</body>
</html>