<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="stylesheet.css">
	<title>Liste des commandes</title>
</head>
<body>
	<h1>Produits</h1>
	<a href="index.php">Retour à l'accueil</a>
	<h2 class="caption h2">Liste des produits</h2>
	<form name="formbarre" method="POST">
	<input type="text" name="barre" id="barre" placeholder="Recherche..." />
	<input type="button" value="Search"/>
	</form>
	<main  class="flex">
	<?php foreach ($result as $key => $value) { ?>
	<section>
		<h3><?php echo $value[1] ?></h3>
		<a href="loneproduct.php?product=<?php echo $value[0] ?>"><?php echo $value[0] ?></a>
		<p>Stock: <?php echo $value[2] ?></p>
		<p><?php echo $value[3] ?>$</p>
	</section>
	<?php } ?>
	</main>
</body>
</html>